<?php
/**
 * Created by PhpStorm.
 * User: aikes
 * Date: 2017/1/4
 * Time: 17:01
 */
namespace Home\Controller;
class PublicController extends BaseController{

    function _initialize(){
//        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function pri_login(){
        if (session('id')) {
            $Mem = M('member');
            $re = $Mem->find(session('id'));
            $this->assign('re',$re);
            $this->display();
        }
        else{
            $this->redirect(U('Home/Index/login'));
        }
    }

    public function login(){
        session('id',null);
        session('nickname',null);
        if ($_POST['submit'] ) {
            if (checkLogin($_POST['username'],$_POST['pwd'])) {
                if (checkIslock($_POST['username'],$_POST['pwd'])) {
                    $us=getMemberbyNickName($_POST['username']);
                    session('id',$us['id']);
                    session('nickname',$us['nickname']);
                    $this->success('登录成功',U('Home/Index/index'));
                }else{
                    $this->success('账号被锁定，请联系管理员',U('Home/Index/login'));

                }
//                 $this->redirect("Index/index");
            } else{
                $this->success('账号密码错误',U('Home/Index/login'));
            }
        }else{
            $this->display('');
        }
    }
}